### ISSUE TITLE
v1.0.0 Release Tracker

### ISSUE THREAD

**Issue by andrewthetechie** [andrewthetechie/pydantic-aioredis#290]
This issue is a checklist for the 1.0.0 release. Checklist items are issues or tasks that should be included in the 1.0.0 release:

- [x] https://github.com/andrewthetechie/pydantic-aioredis/issues/192
- [x] https://github.com/andrewthetechie/pydantic-aioredis/issues/277
- [x] https://github.com/andrewthetechie/pydantic-aioredis/issues/279
- [x] https://github.com/andrewthetechie/pydantic-aioredis/issues/222
- [x] https://github.com/andrewthetechie/pydantic-aioredis/issues/289
- [x] Documentation refresh
- [x] Update all dependencies
- [x] Update nox and workflow to use pytest-cov for coverage rather than coverage

**Comment by andrewthetechie** [comment]
https://github.com/andrewthetechie/pydantic-aioredis/releases/tag/v1.0.0
